
Vagrant.configure("2") do |config|

  # enable cachier globally
  if Vagrant.has_plugin?("vagrant-cachier")
    # disable until this is fixed:
    # https://github.com/fgrehm/vagrant-cachier/issues/113
    #config.cache.scope = :box
  end
end
