
# global Vagrant configuration
Vagrant.configure("2") do |config|

  # enable cachier globally
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box

    # cache bussers, but only if we detect a test-kitchen run
    # see https://github.com/tknerr/bills-kitchen/pull/78
    if Dir.pwd.include? ".kitchen/kitchen-vagrant/"
      config.cache.enable :generic, {
        "busser" => { cache_dir: "/tmp/busser/gems" }
      }
    end
  end
end
