source 'http://rubygems.org'

source 'https://gems.gemfury.com/hUe8s8nSyzxs7JMMSZV8/' # vagrant-1.0.5.1
source 'https://gems.gemfury.com/q2HF2xTDVWamcKx4XCvL/' # knife-solo-0.0.13.1
source 'https://gems.gemfury.com/pznBhaujTsCpFJyTetrF/' # mccloud-0.0.13.2
source 'https://gems.gemfury.com/wHWKHjfyrs7pp9vzNosC/' # cucumber-nagios-0.9.2.2

# core gems we need for cookin'
gem 'vagrant', '1.0.5.1' #, :git => 'https://github.com/tknerr/vagrant.git', :branch => 'bills-kitchen'
gem 'chef', '10.16.2'

# gems for cookbook dependency management
gem 'librarian', '0.0.25' #, :git => 'https://github.com/tknerr/librarian.git', :branch => 'bills-kitchen'
gem 'berkshelf', '1.0.4'
gem 'builder', '3.0.3' # if not specified explicitly `bundle update` will run in an infinite loop, whaaa

# extra gems required by chef on windows (see GH-5)
gem 'ruby-wmi', '0.4.0'
gem 'win32-service', '0.7.2'

# the holistic cookbook testing framework from Opscode
gem 'test-kitchen', '0.7.0.beta.1'
gem 'foodcritic', '1.6.1'

# chefspec and friends
gem 'chefspec', '0.9.0'
gem 'fauxhai', '0.0.4'
gem 'cucumber-nagios', '0.9.2.2' #, :git => 'https://github.com/tknerr/cucumber-nagios.git', :branch => 'bills-kitchen'
gem 'eventmachine', '1.0.0.rc4' # enforce v1.0.0.x - previous versions would not install on Windows


# optional but useful (for dessert)
gem 'veewee', '0.3.1'
gem 'sahara', '0.0.13'

# for creating, backup & restoring chef servers
gem 'knife-server', '0.3.0'

# for bootstrapping via chef-solo
gem 'knife-solo', '0.0.13.1' #, :git => 'https://github.com/tknerr/knife-solo.git', :branch => 'bills-kitchen'

# knife plugin for easier databag management with chef solo
gem 'knife-solo_data_bag', '0.3.0'

# for bootstrapping in da cloud
gem 'mccloud', '0.0.13.2' #, :git => 'https://github.com/tknerr/mccloud.git', :branch => 'bills-kitchen'

# keeps your guest additions in sync with your vagrant version,
# must be enabled explicitly in the project's Vagrantfile
gem 'vagrant-vbguest', '0.5.1'