source 'http://rubygems.org'

source 'https://gems.gemfury.com/hUe8s8nSyzxs7JMMSZV8/' # vagrant-1.0.5.1
source 'https://gems.gemfury.com/wHWKHjfyrs7pp9vzNosC/' # cucumber-nagios-0.9.2.2

# core chef gems we need for cookin'
gem 'chef-tlc-workflow', '0.1.3'

# force use of patched vagrant with windows fixes
gem 'vagrant', '1.0.5.1' #, :git => 'https://github.com/tknerr/vagrant.git', :branch => 'bills-kitchen'


# useful helpers
gem 'knife-audit', '0.2.0'

# for testing outside-in via cucumber
gem 'cucumber-nagios', '0.9.2.2' #, :git => 'https://github.com/tknerr/cucumber-nagios.git', :branch => 'bills-kitchen'
gem 'eventmachine', '1.0.0.rc4' # enforce v1.0.0.x - previous versions would not install on Windows

# for creating, backup & restoring chef servers
gem 'knife-server', '0.3.3'

# keeps your guest additions in sync with your vagrant version,
# must be enabled explicitly in the project's Vagrantfile
gem 'vagrant-vbguest', '0.6.4'